// allow: SIZE_OK - package-root public API barrel contains re-exports only and intentionally preserves one stable root import surface.
export {
  BACKGROUND_MODES,
  COST_REPORT_STATUSES,
  DURATION_SOURCE_STATUSES,
  isSpawnSpecV1,
  RESIDENCY_STATES,
  RESOLVED_MODEL_SOURCES,
  TASK_STATUSES,
  TOKEN_COVERAGE_STATUSES,
  createTaskRecord,
  markRecordLostForReconciliation,
  messageability,
  transitionTaskRecord,
} from "./state"
export type {
  BackgroundMode,
  CostReportStatus,
  DurationSourceStatus,
  LegacyProcessSpawnSpec,
  Messageability,
  PendingSteeringEntry,
  ResidencyState,
  ResolvedModelRecord,
  ResolvedModelSource,
  SpawnSpecV1,
  TaskNotification,
  TaskRecord,
  TaskRecordInput,
  TaskRunStats,
  TaskSpawnSpec,
  TaskStatus,
  TaskTransition,
  TaskTransitionAudit,
  TaskTransitionResult,
  TokenCoverageStatus,
} from "./state"
export { TaskRecordCollisionError, createTaskRecordStore, resolveStateDir } from "./store"
export type {
  ListTaskRecordsResult,
  PersistedTaskEvent,
  StateDirConfig,
  TaskRecordDiagnostic,
  TaskRecordStore,
} from "./store"
export {
  composeStatusLine,
  formatLiveSpend,
  formatRunSpend,
  formatStatusTarget,
  formatTargetIdentity,
  formatTargetWithModel,
  taskIdentityLabel,
  toolCountSuffix,
} from "./status-line"
export type { StatusLineInput, StatusLineStats, StatusTargetInput, TaskIdentityInput } from "./status-line"
export { TASK_SUMMARY_MAX_LENGTH, clampTaskSummary } from "./task-summary"
export {
  assistantLastLine,
  createChildProgress,
  formatToolActivity,
  type ToolProgressDetails,
} from "./progress"
export { createMinimalSenpiResourceLoader } from "./senpi/minimal-resource-loader"
export type { MinimalSenpiResourceLoaderOptions } from "./senpi/minimal-resource-loader"
export {
  MEMBER_IDENTITY_ENV,
  SenpiTeamSpecError,
  TEAM_LEAD_SENTINEL,
  ensureTeamRuntimeDirs,
  isTeamMemberProcess,
  loadTeamRegistry,
  normalizeSenpiTeamSpec,
  resolveProjectTeamSpecPath,
  resolveTeamMemberInboxDir,
  resolveTeamRuntimeDirs,
  teamStorageBaseDir,
  validateSenpiTeamMembers,
} from "./team"
export type {
  LoadTeamRegistryInput,
  LoadTeamRegistryResult,
  NormalizeSenpiTeamSpecOptions,
  SenpiTeamMemberPorts,
  SenpiTeamSpecErrorCode,
  TeamRegistryEntry,
  TeamRegistryError,
  TeamRuntimeDirs,
  TeamSpecSource,
} from "./team"
export {
  BUILTIN_CATEGORY_DEFAULTS,
  CATEGORY_DESCRIPTIONS,
  CATEGORY_PROMPT_APPENDS,
  DEFAULT_CATEGORIES,
  resolveAvailableCategoryNames,
  resolveCategory,
} from "./category"
export type {
  BuiltinCategoryDefinition,
  CategoryModelSelection,
  CategoryResolutionResult,
  ResolvedChildSpec,
  SenpiModelPort,
  SenpiModelRegistryPort,
} from "./category"
export {
  DEFAULT_MAX_CHILD_DEPTH,
  InProcessRunner,
  RunnerError,
  buildSubagentPrompt,
  createChildResourceLoader,
  filterSharedParentTools,
  isTaskOrTeamFamilyTool,
  mergeChildCustomTools,
} from "./runners"
export type {
  ChildHandle,
  ChildSession,
  ChildSessionEvent,
  ChildSessionListener,
  ChildSpec,
  CreateChildSession,
  DepthPolicy,
  InProcessRunnerOptions,
  RunnerFailure,
  RunnerOutcome,
  SharedToolFilterOptions,
  SubagentPromptInput,
} from "./runners"
export {
  RpcCommandError,
  RpcProcessRunner,
  RpcProtocolClient,
  buildAutoUiResponse,
  buildChildArgs,
  buildRpcSpawn,
  OMO_SENPI_TASK_RPC_CHILD,
  classifyChildExit,
  createRpcChildHandle,
  detectBunBinary,
  mapExitOutcomeToError,
  parseExtensionEntries,
  resolveChildSessionDir,
  resolveSenpiExecutable,
  resolveSenpiLauncher,
  tailStderr,
  terminateRpcChild,
} from "./runners"
export type {
  ChildEventListener,
  ChildExitFacts,
  ChildExitInput,
  ChildExitOutcome,
  CreateRpcChildHandleOptions,
  MalformedLineHandler,
  RpcChildHandle,
  RpcProcessRunnerOptions,
  RpcProtocolClientOptions,
  RpcRunnerSpec,
  RpcSpawnDescriptor,
  RpcSpawnRuntime,
  SenpiLauncher,
  RunnerErrorFacts,
  TerminateOptions,
} from "./runners"
export {
  NameRegistry,
  TaskConcurrency,
  adaptInProcessHandle,
  adaptRpcHandle,
  createInProcessManagedRunner,
  createParentRegistrySessionContext,
  createRpcManagedRunner,
  createTaskManager,
  decideDepthPolicy,
  findModelReference,
  resolveExecutionMode,
} from "./manager"
export type {
  AdmitResident,
  ChildModelRegistry,
  ChildPlanner,
  ContinueDelivery,
  ContinueResult,
  DepthDecision,
  DepthPolicyInput,
  ExecutionMode,
  ExecutionModeSources,
  InProcessRunnerLike,
  InProcessSessionContext,
  InProcessSessionContextProvider,
  ListScope,
  ListedTask,
  ManagedChildEvent,
  ManagedChildHandle,
  ManagedChildListener,
  ManagedRunner,
  ManagedStartSpec,
  ManagerStartSpec,
  NameRegistration,
  ParentModelRegistryResolver,
  PlanResolution,
  PlanResolutionError,
  ResolvedChildPlan,
  RpcRunnerLike,
  SpawnAdmission,
  StartResult,
  TaskConcurrencyConfig,
  TaskManager,
  TaskManagerOptions,
  TrustedRespawnLaunch,
  TrustedRespawnLaunchResolver,
} from "./manager"
export {
  AGENT_INVOCATION_CONDITIONS,
  BUILTIN_AGENTS,
  BUILTIN_AGENT_DEFAULTS,
  CURATED_READONLY_AGENT_NAMES,
  ULW_REVIEWER_AGENT_NAMES,
  EMPTY_SKILL_INVOCATIONS,
  PLAN_GATED_AGENT_NAMES,
  defineAgent,
  evaluateInvocationGuard,
  invocationConditionForAgent,
  loadAgents,
  mapOmoConfigAgents,
  registerAgent,
  resolveAgent,
  resolveToolRule,
} from "./agents"
export type {
  AgentInvocationCondition,
  AgentModelCandidate,
  AgentModelEntry,
  AgentModelUnavailableResult,
  AgentNotFoundResult,
  AgentResolutionResult,
  AgentDefinition,
  AgentDefinitionInput,
  AgentLoaderDiagnostic,
  AgentLoaderDiagnosticKind,
  AgentToolRule,
  InvocationGuardVerdict,
  LoadAgentsOptions,
  LoadAgentsResult,
  ResolveAgentOptions,
  ResolvedAgentResult,
  SkillInvocationState,
} from "./agents"
export { buildNoticeBox, noticeTone } from "./notice-box"
export type { NoticeLine, NoticeSpec, NoticeTheme, NoticeTone } from "./notice-box"
// Render-runtime lazy boundary: the task component awaits this at registration so the render
// helpers above can read the pi-tui namespace synchronously without statically binding the
// omo-task.js/omo-member.js blobs to the pi-tui barrel.
export { loadPiTui } from "./lazy/pi-tui"
export {
  buildCompletionDetails,
  buildCompletionMessage,
  completionMessageLines,
  createCompletionNotifier,
  DAG_VERIFICATION_DIRECTIVE,
  routeCompletion,
  shouldNotifyStatus,
} from "./completion"
export type {
  CompletionDetails,
  CompletionNotifier,
  CompletionNotifierDeps,
  CompletionNotifierStore,
  CompletionRequest,
  DeliveredDecision,
  FlushInput,
  FlushResult,
  NotifyResult,
  ParentNotifier,
  ParentNotifierMessage,
  ParentState,
  RoutingDecision,
  SkipReason,
  TransitionReason,
} from "./completion"
export {
  AgentLimitReached,
  createTaskLifecycle,
  getLifecycleReattachPorts,
  registerLifecycleReattachPorts,
} from "./lifecycle"
export type {
  AdmissionResult,
  CleanupResult,
  DestroyCause,
  LifecycleDeps,
  LifecycleReattachPorts,
  ProcessSignaller,
  ReattachPort,
  ReattachResult,
  ReconcileOutcome,
  ReconcileOutcomeKind,
  ReconcileResult,
  ResidentHandle,
  ResidentSummary,
  ResidencyRegistry,
  RespawnPort,
  RespawnResult,
  SuspendFailure,
  SuspendInput,
  SuspendSummary,
  TaskLifecycle,
} from "./lifecycle"
export { DEFAULT_SEND_DELIVERY, createSteeringEngine } from "./steering"
export type {
  CancelOutcome,
  DestructionCause,
  DestructionPort,
  InterruptOutcome,
  SendDelivery,
  SendInput,
  SendOutcome,
  SteeringEngine,
  SteeringPort,
} from "./steering"
export {
  TASK_PROMPT_GUIDELINES,
  TASK_PROMPT_SNIPPET,
  TASK_TOOL_NAME,
  TaskToolParams,
  buildSkillPrepend,
  buildTaskExecute,
  buildTaskToolDescription,
  resolvePromptCacheSafeWaitSeconds,
  createFsSkillLoader,
  createTaskTool,
  evaluateSpawnPolicy,
  excerptRendererPromptText,
  excerptRendererText,
  joinRendererTokens,
  linesComponent,
  listTaskAgents,
  listTaskCategories,
  normalizeRendererText, recordSummary,
  rendererVisibleWidth,
  statusThemeColor,
  taskCallLines,
  taskResultLines,
  validateTaskTarget,
  waitForForegroundTask,
} from "./tools/task"
export type {
  ForegroundWaitInput,
  ForegroundWaitOptions,
  ForegroundWaitResult,
  ResolveAncestry,
  ScheduleDeadline,
  SkillLoader,
  SkillResolution,
  TaskAgentInfo,
  TaskAncestry,
  TaskCategoryInfo,
  TaskTargetError,
  TaskTargetErrorCode,
  TaskTargetSelection,
  TaskToolContext,
  SpawnPolicyVerdict,
  TaskToolDeps,
  TaskToolDetails,
  TaskToolMode,
  TaskToolParamsStatic,
} from "./tools/task"
export {
  TaskCancelParams,
  MemberScopedTaskSendParams,
  TaskSendParams,
  clampWaitTimeout,
  createMemberScopedTaskSendTool,
  createTaskCancelTool,
  createTaskSendTool,
  defaultResolveCallerSessionId,
  finalResponseHead,
  isTerminalStatus,
  runTaskCancel,
  runTaskSend,
  toolResult,
} from "./tools/control"
export type {
  CallerSessionResolver,
  CancelManager,
  CancelResultDetails,
  CancelToolResult,
  MemberScopedTaskSendDeps,
  MemberScopedTaskSendInput,
  SendManager,
  SendResultDetails,
  SendToolResult,
  DefaultTeamRunIdResolution,
  SessionIdCarrier,
  TaskCancelDeps,
  TaskCancelInput,
  TaskSendDeps,
  TaskSendInput,
  TaskSendTeamRouting,
  WaitBounds,
} from "./tools/control"
export {
  TRANSCRIPT_MAX_CHARS,
  TaskOutputParams,
  buildTaskSnapshot,
  childSessionDir,
  createTaskOutputTool,
  defaultTranscriptReader,
  parseSessionTranscript,
  readEventLogTranscript,
  readSessionDirTranscript,
  renderTranscript,
  runTaskOutput,
} from "./tools/output"
export type {
  LostBreadcrumbs,
  OutputManager,
  RenderOptions,
  RenderedTranscript,
  SuspendedDetails,
  TaskOutputDeps,
  TaskOutputDetails,
  TaskOutputInput,
  TaskOutputToolResult,
  TaskSnapshot,
  TranscriptEntry,
  TranscriptReadResult,
  TranscriptReader,
  TranscriptSource,
} from "./tools/output"
export {
  buildPeerMessageEnvelope,
  buildTeamMessage,
  createLeadPoller,
  createIncrementalSessionMarkerIndex,
  DEFAULT_STALE_RESERVATION_TTL_MS,
  MEMBER_EXTENSION_BUNDLE_NAME,
  parseMemberExtensionEnv,
  reclaimStaleTeamReservations,
  reconcileTeamMailboxOnSessionStart,
  resolveMemberExtensionEntryPath,
  createLeadDeliveryJournal,
  createTeamMemberRespawnLaunchResolver,
  TeamMemberRespawnLaunchError,
  sendTeamMessage,
} from "./team"
export type {
  BuildTeamMessageOptions,
  LeadDeliveryJournal,
  LeadDeliveryJournalOptions,
  LeadInjection,
  LeadInjectionSink,
  LeadPollFilter,
  LeadPoller,
  LeadPollerDeps,
  MemberExtensionConfigErrorCode,
  MessagingEngineDeps,
  ParsedMemberExtensionEnv,
  ReclaimResult,
  ReconcileTeamMailboxDeps,
  SessionMarkerExtractor,
  SessionMarkerIndex,
  SessionSliceReader,
  SendTeamMessageInput,
  SendTeamMessageResult,
} from "./team"
export {
  approveShutdown,
  canClaimTeamTask,
  claimTeamTask,
  createTeamTask,
  DELETABLE_MEMBER_STATUSES,
  getTeamTask,
  isMemberDeletable,
  listTeamTasks,
  rejectShutdown,
  requestShutdown,
  SenpiShutdownError,
  TeamTaskAlreadyClaimedError,
  TeamTaskBlockedByError,
  TeamTaskCrossOwnerUpdateError,
  TeamTaskInvalidTransitionError,
  updateTeamTaskStatus,
} from "./team"
export type {
  ApproveShutdownDeps,
  CreateTeamTaskInput,
  RejectShutdownDeps,
  RequestShutdownDeps,
  SenpiShutdownErrorCode,
  ShutdownMessageKind,
  ShutdownMessenger,
  ShutdownOutboundMessage,
  TeamTaskFilter,
  TeamTasklistContext,
} from "./team"
export {
  createTeam,
  deleteTeam,
  isOwnedTeamMemberTask,
  parseTeamMemberTaskIdentity,
  readMemberTaskMap,
  refreshTeamMemberStatuses,
  SenpiTeamRuntimeError,
  toTeamCoreConfig,
} from "./team"
export type {
  CreateTeamDeps,
  CreateTeamResult,
  CreatedMemberInfo,
  DeleteTeamDeps,
  DeleteTeamResult,
  MemberStatusPort,
  MemberTaskMap,
  RefreshTeamMemberStatusesDeps,
  SenpiTeamRuntimeErrorCode,
  SpawnMemberExtensionConfig,
  TeamCoreConfig,
  TeamMemberExtensionConfig,
  TeamMemberOwnershipDeps,
  TeamMemberTaskIdentity,
  TeamRuntimeManagerPort,
  TeamMemberRespawnLaunchResolverOptions,
  TeamMemberRespawnLaunchErrorCode,
} from "./team"

export * from "./tools/team"
